### PR TITLE
dataworld: improve error message

### LINKED ISSUE #389: Improve error handling for data.world queries
Currently, the data.world connector makes assumptions about the response payload that are not met in case of errors. Instead, the connector should expect a different payload in case of errors and make good use of it to inform the user about what's wrong with their SQL query.

image

### PR DESCRIPTION
**Pull request by n-riesco**
@kndungu @rflprr Since you are familiar with the code, would you like to review this PR?

* data.world: send error message of failed queries.

* Preview: repect line breaks in error messages and use mono-space font.

Closes #389 

screenshot from 2018-03-02 17-49-55

### CODE REVIEW

File: backend/persistent/datastores/dataworld.js [hunk 1]
```diff
@@ -88,6 +88,11 @@ export function query(queryString, connection) {
     body: params
   })
   .then(res => {
+    if (res.status !== 200) {
+      return res.text().then(body => {
```
Comment (kndungu) [inline backend/persistent/datastores/dataworld.js]: Unfortunately not all error messages are returned as text, some come in the form of an error object.

For example, `401`s produce the following response:

```
{ "code": 401, "request": "06d583b7-afbf-48ca-b1b8-961ed0b092a0", "message": "Unauthorized" }
```

Displaying the entire object is unnecessary since only the content of `message` is useful to the user.

We could replace this bit of code with:
 
```
if (res.status !== 200) {
  return res.text().then(body => {
    try {
      const errorObject = JSON.parse(body);
      throw new Error(errorObject.message);
    } catch (err) {
      if (err.name === 'SyntaxError') {
        throw new Error(body);
      }
      
      throw new Error(err.message);
    }
  });
}
```

File: app/components/Settings/Preview/Preview.react.js [hunk 2]
```diff
@@ -66,14 +66,24 @@ class Preview extends Component {
         let rows = [];
         let columnNames = [];
         let isLoading = false;
-        let errorMsg = '';
         let successMsg = '';
 
+        let errorMsg = '';
+        function setErrorMsg(error) {
+            if (error && error.content && error.content.error && error.content.error.message) {
```
Comment (kndungu) [inline app/components/Settings/Preview/Preview.react.js]: To be more succinct we could go with:

```
try {
  errorMsg = error.content.error.message;
} catch(err) {
  errorMsg = JSON.stringify(error);
} finally {
  errorMsg = String(errorMsg).trim();
}
```

File: backend/persistent/datastores/dataworld.js (hunk 1 above)
Comment (n-riesco) [reply backend/persistent/datastores/dataworld.js]: I've handled this in [Preview.react.js](https://github.com/n-riesco/plotly-database-connector/blob/18b120e3d759888e040f5e5bf4b292c3f4c4e31d/app/components/Settings/Preview/Preview.react.js#L71-L80) so that other connectors benefit from this PR.

**Comment by n-riesco** [comment]
@kndungu I've updated the PR using your comments and rebased it against master. I'll merge it, if you're happy with the latest changes.

File: backend/persistent/datastores/dataworld.js (hunk 1 above)
Comment (kndungu) [reply backend/persistent/datastores/dataworld.js]: Agreed, the changes in `Preview.react.js` allows all connectors to display a custom error message instead of simply "stringifying" the error thrown.

The change I'm suggesting has to do with the custom error that the data.world connector throws.

When the response from the API is a string it will be displayed as is, e.g.

When it is a `400` the response from the API is a string specifying the specific problem (e.g. `'(' expected but 'BADSELECT' found... `)

But when the response is an object the entire object is shown, e.g.

When it is a `401` the response from the API is an object that is overly verbose (`{ "code": 401, "request": "06d583b7-afbf-48ca-b1b8-961ed0b092a0", "message": "Unauthorized" }`)

As it currently stands this entire object will be displayed to the user, the change I'm proposing will result in only the contents of the `message` attribute being displayed to the user i.e. `Unauthorized`

Comment (n-riesco) [reply backend/persistent/datastores/dataworld.js]: @kndungu My bad! Your first explanation was clear enough.

I've fixed this in https://github.com/plotly/falcon-sql-client/pull/394/commits/11950d1808af4b8449b02ea43548fcc0a52fa625 . I've also tested it manually.

Please, let me know if it looks OK to you.

Comment (kndungu) [reply backend/persistent/datastores/dataworld.js]: @n-riesco no worries!

Yes it does! More elegant than my suggested fix :shipit:
