### PR TITLE
oauth: check status code before parsing body

### LINKED ISSUE #285: test failure in routes.spec.js (oauth API)
One of the first bug catches thanks to PR #284:

- If `/v2/users/current` fetch doesn't succeed (status 200), then [here](https://github.com/plotly/falcon-sql-client/blob/d470cbcbd075214c6079f5606a33eda60d2c27fd/backend/plugins/authorization.js#L60) body can't be parsed as JSON.

Log from CircleCI

```
  1) Routes: "before each" hook for "doesn't save connections if they already exist":
     Error: Expected status: 200. Status: 500. Body: {"error":{"message":"invalid json response body at https://api.plot.ly/v2/users/current reason: Unexpected token < in JSON at position 1"}}.
      at assertResponseStatus (test/backend/utils.js:13:25)
      at Context.<anonymous> (test/backend/routes.spec.js:444:15)
```

### PR DESCRIPTION
**Pull request by n-riesco**
Fixes #285

### CODE REVIEW

**Comment by n-riesco** [comment]
@tarzzz Would you review this one, please?
With this PR, oauth checks the status code before trying to parse the body into json. If the status code isn't 200, an error message that contains the response body is created.

**Comment by tarzzz** [comment]
LGTM so far.. Can you please add a test which checks that proper error message is returned in this condition..

File: backend/plugins/authorization.js [hunk 1]
```diff
@@ -57,26 +57,32 @@ export function PlotlyOAuth(electron) {
         fetch(`${getSetting('PLOTLY_API_URL')}/v2/users/current`, {
             headers: {'Authorization': `Bearer ${plotlyAuthToken}`}
         })
-        .then(userRes => userRes.json().then(userMeta => {
+        .then(userRes => {
             if (userRes.status !== 200) {
-                res.json(401, {error: {message: 'Please login to access this page.'}});
-                return next(false);
+                return userRes.text().then(body => {
```
Comment (tarzzz) [inline backend/plugins/authorization.js]: Instead of checking for status code, we should check for `userRes.json().username` .. If it is `null`, it means that the user was not authenticated with Plotly (or the accessToken has expired)

Comment (n-riesco) [reply backend/plugins/authorization.js]: @tarzzz 
> Instead of checking for status code, we should check for userRes.json().username

Addressed in https://github.com/plotly/falcon-sql-client/pull/368/commits/bc901daf225297be8bd4198346b4124a0be87e41

**Comment by n-riesco** [comment]
@tarzzz 💃 ?

**Comment by tarzzz** [comment]
We should be able to get rid of this check in both the places:

```
            if (userRes.status !== 200) {
                return userRes.text().then(body => {
                    const errorMessage = `Error fetching user. Status: ${userRes.status}. Body: ${body}.`;
                    Logger.log(errorMessage, 0);
                    res.json(500, {error: {message: errorMessage}});
                    return next();
                });
            }
```

Since this will never happen .. Please remove this and 💃 then ..

**Comment by tarzzz** [comment]
Actually, I don't quite understand the issue here. From the top comment in issue:

> If /v2/users/current fetch doesn't succeed (status 200), then here body can't be parsed as JSON.

But this should **Never** happen. Can you please check if something else is going on here..

**Comment by n-riesco** [comment]
@tarzzz We see this error when we get the loading-page error (snippet taken from a failure in CircleCI):

```html
        <p class="error-page-text">Uh oh. An error occurred while loading this page.</p>
        <p class="error-page-subtext">
            Try refreshing the page. If the problem persists, open an issue at <a href="https://support.plot.ly?utm_campaign=build-failed&utm_medium=email&utm_source=notification">support.plot.ly</a>.
            Thanks for your patience and sorry for the delay.
        </p>
```

**Comment by tarzzz** [comment]
This is a Plotly `500` error page. Can you please give more context as to when it occurs. I do not understand what you mean by 'loading-page error'. This could be a bug on Plotly Cloud side, but I need more information to tell more about it.

**Comment by n-riesco** [comment]
@tarzzz The Plotly `500` error page is what I mean by the loading-page error. We often see this error in CircleCI, e.g. https://circleci.com/gh/plotly/falcon-sql-client/3720?utm_campaign=build-failed&utm_medium=email&utm_source=notification . With this PR, we will be able to know for sure.

**Comment by tarzzz** [comment]
Ok, from an initial look at that circle CI failure, it seems that `grids/${fid}/content` or `updateGrid` or `createGrid` is giving a 500 (probably due to malformed content, but not 💯 )

I am sceptical if this will help with that particular error, but I am okay with this code being merged, because it generally stabilizes the code.. !!
